### ISSUE TITLE
Undefined variable $cw php 8.0.1 laravel 8.6

### ISSUE THREAD

**Issue by AndrewRamyE** [mccarlosen/laravel-mpdf#102]
the issue Undefined variable $cw
vendor/mpdf/mpdf/src/Mpdf.php:3991
this happen on some fonts

**Comment by mccarlosen** [comment]
Hi, what fonts do you use?

**Comment by AndrewRamyE** [comment]
the font was 'sans-serif' then change it to 'XBRiyaz' it works fine

**Comment by mccarlosen** [comment]
I use `sans-serif` and it works fine.

**Comment by AndrewRamyE** [comment]
i work fine fine for 5 months
