### ISSUE TITLE
psr error msg !

### ISSUE THREAD

**Issue by abotariq2010** [mccarlosen/laravel-mpdf#107]
I simply follow the example and i got 

Declaration of Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void

**Comment by Girevik1** [comment]
Try adding latest version "carlos-meneses/laravel-mpdf": "2.1.10" to composer.json. It`s version support php 8.0
It helped me
