### ISSUE TITLE
Undefined variable $cw php 8.0.1 laravel 8.6

### ISSUE THREAD

**Issue by AndrewRamyE** [mccarlosen/laravel-mpdf#108]
when i make default values to  $cw='';
       $glyphIDtoUni='';
it goes to see file_get_contents(/tmp/mpdf/ttfontdata/xbriyaz.GSUBGPOStables.dat): Failed to open stream: No such file or directory 
and this file is not created
their is an option to not use cash because it is not saved 
this issue repeated every 2 or 3 monthes and when i change the default_font it works agin 
i need simple way to make the package never use cash ,in my case the cash not saved

**Comment by mccarlosen** [comment]
This error is not related to `laravel-mpdf`. On the other hand, there is not enough information to understand the problem.

Closed for now. You can reopen it at any time.
