### ISSUE TITLE
Footer working only in last page

### ISSUE THREAD

**Issue by GGarnize** [mccarlosen/laravel-mpdf#109]
`$footer = '<span>Página {PAGENO} de {nbpg}</span>'`
`$mpdf = PDF::chunkLoadView('<html-separator/>', 'pdf.bladepdf', $data);`
`$mpdf->getMpdf()->SetHTMLFooter($footer);`

`<style>
        @page {
            footer: page-footer;
        }
</style>`
`<htmlpagefooter name="page-footer">
    <div style="padding: 10px 10px;">
        <table width="100%">
            <tr>
                <td width="33%" align="center" style="font-style: italic;">Página {PAGENO} de {nbpg}</td>
            </tr>
        </table>
    </div>
</htmlpagefooter>`

When Pdf generate 2 or more pages, It works, but when it have just one page, 
`SetHTMLFooter` Not cover the footer in blade

**Comment by mccarlosen** [comment]
If you use the `<htmlpagefooter />` tag, it is no longer necessary to use the `SetHTMLFooter` method.

Remember to define the `@page` inside a `head` tag:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
	@page {
	    footer: page-footer;
	}
    </style>
</head>
<body>
	
    <htmlpagefooter name="page-footer">
        Your Footer Content
    </htmlpagefooter>
	
    <h1>Hola Mundo!</h1>

</body>
</html>
```

**Comment by GGarnize** [comment]
I'm trying set custom footer just to last page, and when document have 2 or more pages, my code works, but when this have unique page, my `SetHTMLFooter` not overwrite the tag `<htmlpagefooter />`, the function just overwrite when have more pages, then the function change the footer of last page.
