### ISSUE TITLE
LoggerInterface Issue

### ISSUE THREAD

**Issue by sgtcoder** [mccarlosen/laravel-mpdf#110]
With the latest update we are getting this error again:
```
Declaration of Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void
```

**Comment by mccarlosen** [comment]
Hello! What version of Laravel and PHP are you using? This is a bug inherent in mPDF. You can find more information on the subject here: [Issue](https://github.com/mpdf/mpdf/issues/1622)

**Comment by sgtcoder** [comment]
Latest version of Laravel 9. And PHP 8.1.

So do I contact mpdf?

**Comment by mccarlosen** [comment]
Delete the `composer.lock` file in your laravel project and install the latest version of mPDF. Run this command:

`composer require mpdf/mpdf 8.1.0`

**Comment by sgtcoder** [comment]
Hi, thank you, that worked.
