### ISSUE TITLE
To start using Laravel,  laravel 9.52.0PHP 8.2.1 

### ISSUE THREAD

**Issue by HazemAyyad** [mccarlosen/laravel-mpdf#118]
****

```
'providers' => [
    Mccarlosen\LaravelMpdf\LaravelMpdfServiceProvider::class
]
'aliases' => [
    'PDF' => Mccarlosen\LaravelMpdf\Facades\LaravelMpdf::class
]
```

**This Right**
```
'providers' => [
 Meneses\LaravelMpdf\LaravelMpdfServiceProvider::class
]
'aliases' => [
    'PDF' => Meneses\LaravelMpdf\Facades\LaravelMpdf::class
]
```
replace **mpdf.php** in path         => vendor\mpdf\mpdf\mpdf.php
replace **otl.php** in path             => vendor/mpdf/mpdf/classes/otl.php
replace **ttfontsuni.php** in path =>vendor/mpdf/mpdf/classes/ttfontsuni.php
replace **grad.php** in path         =>vendor/mpdf/mpdf/classes/grad.php

**Comment by mccarlosen** [comment]
Hi, @HazemAyyad!

I recently updated the repository from 2.1.10 to 2.1.11. But I made an error changing the namespace from `Meneses\...` to `Mccarlosen\...` without thinking that it would break the users' codebase during the upgrade.

The correct namespace is:

```php
'providers' => [
    // ...
    Mccarlosen\LaravelMpdf\LaravelMpdfServiceProvider::class
]
```
```php
'aliases' => [
    // ...
    'PDF' => Mccarlosen\LaravelMpdf\Facades\LaravelMpdf::class
]
```
My suggestion is that you uninstall and reinstall again the package. I hope to help you.

**Comment by HazemAyyad** [comment]
hi @mccarlosen 
but composer install 1.1 
![Screenshot 2023-02-21 083951](https://user-images.githubusercontent.com/28767502/220266865-2f4bbc68-8e9d-4895-920b-2e3367ea9d32.png)

**Comment by mccarlosen** [comment]
What are your PHP, composer, and php-cli versions?

Verify your environment. If you are using PHP 8.1 it will install the default `laravel-mpdf@^2.1`

**Comment by HazemAyyad** [comment]
[image: image.png]

**Comment by mccarlosen** [comment]
Right! You may use PHP 8.1. The current package version is not updated for PHP 8.2. 

Wait a little longer. I will update it as soon as I can.

**Comment by ZayRTun** [comment]
Hi, any update on this issue?
