### ISSUE TITLE
Laravel How to use PDF in Helpers

### ISSUE THREAD

**Issue by coderbhaai** [mccarlosen/laravel-mpdf#120]
If we try to use "use PDF" in helper after including this in config, it gives error.

Basically, the path to pdf is required in a helper and gives the below error.

The use statement with non-compound name 'PDF' has no effect in helper page.

**Comment by arif98741** [comment]
I am using this package without facing any issue at all.

**Comment by mccarlosen** [comment]
You can use:

```php
use Meneses\LaravelMpdf\Facades\LaravelMpdf as PDF;
```
or
```php
$pdf = \App::make('mpdf.wrapper');
$pdf = $pdf->loadView('test');
return $pdf->stream();
```
