### ISSUE TITLE
Styling The Generated PDF

### ISSUE THREAD

**Issue by omaru-kamara** [mccarlosen/laravel-mpdf#121]
Hi, how do I style the pdf generated as specified here. Please kindly provide help in styling the pdf. Thanks.

**Comment by Ohyoo-Labs** [comment]
No, that don't work very well. Only some styles are recognized. E.g: font-family - wrong, transform - wrong.

**Comment by omaru-kamara** [comment]
Thanks for the response. I have tried the embedded styling, but nothing
seems to work.

Hoping to resolve this issue.
Further help will be appreciated.

Omaru A. Kamara
*EEEE:* ***@***.***
*Contacts: +231770006316 / +231880461645*
*Highest Education:* BSc, System Administration, Starz University (Honor -
Magna Cum laude - 3.6 GPA)
*Work Position:*
*Software/Application Developer, Liberia HR Jobs Board Inc.*
*Co-founder, Techpro Africa*

**Comment by omaru-kamara** [comment]
Thanks, I'll check it out.
Omaru A. Kamara
*EEEE:* ***@***.***
*Contacts: +231770006316 / +231880461645*
*Highest Education:* BSc, System Administration, Starz University (Honor -
Magna Cum laude - 3.6 GPA)
*Work Position:*
*Software/Application Developer, Liberia HR Jobs Board Inc.*
*Co-founder, Techpro Africa*
