### ISSUE TITLE
Laravel 10 - When ?

### ISSUE THREAD

**Issue by realtebo** [mccarlosen/laravel-mpdf#125]
Is it planned to update this package to be compatibile with Laravel 10 (and PHP 8.2) ?

We got complaint about PSR-<something> compatibility

**Comment by finwe** [comment]
Now, I have just installed this package alongside Laravel 10.2 on PHP 8.2.

Maybe try it first and then share exact problems you are having.

**Comment by finwe** [comment]
(this should read "not compatible with psr/http-message ^2.0" and be reported in mpdf repository directly)

**Comment by saraswat19** [comment]
I am getting this error on laravel 10

<img width="1468" alt="Screenshot 2023-05-25 at 01 14 31" src="https://github.com/mccarlosen/laravel-mpdf/assets/6272778/d17b41be-d06b-48d5-8bc1-a0e5d58b52fb">

**Comment by finwe** [comment]
@saraswat19 your installed mPDF version is <7.0, probably 6.1.3 which is far from compatible with PHP 8. Make sure your dependencies allow the latest mPDF 8.x version.

**Comment by saraswat19** [comment]
> @saraswat19 your installed mPDF version is <7.0, probably 6.1.3 which is far from compatible with PHP 8. Make sure your dependencies allow the latest mPDF 8.x version.

Thank you. That fixed it.
