### ISSUE TITLE
mPDF requirement needs to be updated to 8.1.6

### ISSUE THREAD

**Issue by Stucks** [mccarlosen/laravel-mpdf#132]
After installing on Laravel 10 I was getting the psr/log error. Turns out that mPDF 8.0 was being installed. Composer.json need to be updated to install 8.1.6.

For anyone else getting this error, run `composer require mpdf/mpdf v8.1.6 -W` to install the correct version.

**Comment by mccarlosen** [comment]
All right! it's fixed. Update to the `v2.1.13` version.
