### ISSUE TITLE
footer is working only on last page

### ISSUE THREAD

**Issue by masadi** [mccarlosen/laravel-mpdf#23]
```php
$pdf = PDF::loadView('transaksi.pdf_'.$query, $data, [], [
	'orientation' => 'L',
	'margin_footer' => '5',
]);
$pdf->getMpdf()->SetTitle($title);
$pdf->getMpdf()->SetAuthor(config('settings.app_name'));
$pdf->getMpdf()->SetCreator(config('settings.app_name'));
$pdf->getMpdf()->SetSubject($title);
$pdf->getMpdf()->setFooter('Dicetak dari Aplikasi '.config('settings.app_name').'||Halaman {PAGENO} dari {nbpg}');
```

**Comment by DesarrolloSiget** [comment]
Hello,

You can try writing header and footer in view html with

<htmlpageheader name="page-header">
        {!! $header !!}
</htmlpageheader>
<htmlpagefooter name="page-footer">
        {!! $footer !!}
</htmlpagefooter>

**Comment by DesarrolloSiget** [comment]
Hello,

You can try writing header and footer in view html with tags

`<htmlpageheader name="page-header">
        {!! $header !!}
 </htmlpageheader>

 <htmlpagefooter name="page-footer">
        {!! $footer !!}
 </htmlpagefooter>`

**Comment by DesarrolloSiget** [comment]
Hello,

You can try writing header and footer in view html with tags

![imagen](https://user-images.githubusercontent.com/49963285/65254861-8a481080-dac2-11e9-9f87-d0428c35b0c4.png)
