### ISSUE TITLE
Print PDF Blank

### ISSUE THREAD

**Issue by DesarrolloSiget** [mccarlosen/laravel-mpdf#24]
Hello,

I am  development a template editor and which i try print in pdf  (with method stream) a document in blank, this result how output in html 

![imagen](https://user-images.githubusercontent.com/49963285/65255165-0b9fa300-dac3-11e9-8f5d-226ae7f3e70e.png)

**Comment by mccarlosen** [comment]
If the body tag is empty, that is the default mpdf output, as invalid html.

But the trick can be the following:

```php
$pdf = PDF::loadView('pdf.document');
$pdf->getMpdf()->WriteHTML("&nbsp;");
return $pdf->stream('document.pdf');
```

or

controller.php
```php
$pdf = PDF::loadView('pdf.document');
return $pdf->stream('document.pdf');
```
view.blade.php
```html
<!DOCTYPE html>
<html>
<body>
    &nbsp;
</body>
</html>
```
