### ISSUE TITLE
How to add new page

### ISSUE THREAD

**Issue by sanal2net** [mccarlosen/laravel-mpdf#29]
How can we create a new page?

$pdf = PDF::loadView('pdf.document',$data);
$pdf->getMpdf()->AddPage();
$pdf->loadView('pdf.document',$data);

The above code didn't work.

**Comment by simadesign** [comment]
Change this line:  
$pdf->loadView('pdf.document',$data); 
to 
return $pdf->stream('document.pdf');

**Comment by mccarlosen** [comment]
You have several options. View docs [here](https://mpdf.github.io/paging/page-breaks.html)

```php
$pdf = PDF::loadView('pdf.document');
// get instance
$mpdf = $pdf->getMpdf();
// add page
$mpdf->AddPage();

return $pdf->stream('document.pdf');
```
Or

```css
<style>
   @page { sheet-size: A3-L; }
</style>
```
```html
<h1>Page 1</h1>
<pagebreak></pagebreak>
<h1>Page 2</h1>
```

**Comment by theambidextrous** [comment]
H

> You have several options. View docs [here](https://mpdf.github.io/paging/page-breaks.html)
> 
> ```
> $pdf = PDF::loadView('pdf.document');
> // get instance
> $mpdf = $pdf->getMpdf();
> // add page
> $mpdf->AddPage();
> 
> return $pdf->stream('document.pdf');
> ```
> 
> Or
> 
> ```css
> <style>
>    @page { sheet-size: A3-L; }
> </style>
> ```
> 
> ```
> <h1>Page 1</h1>
> <pagebreak></pagebreak>
> <h1>Page 2</h1>
> ```

how is the first option an option in the first place? I do not get..
 assume you want to add multiple laravel/blade views as pages. how does option 1 work?
