### ISSUE TITLE
costume fonts not working

### ISSUE THREAD

**Issue by alomari-abdulhadi** [mccarlosen/laravel-mpdf#31]
I use in config/Mpdf.php this code

``<?php
return [
    'mode'                 => '',
    'format'               => 'A4-L',
    'default_font_size'    => '12',
    'default_font'         => 'sans-serif',
    'margin_left'          => 10,
    'margin_right'         => 10,
    'margin_top'           => 10,
    'margin_bottom'        => 10,
    'margin_header'        => 0,
    'margin_footer'        => 0,
    'orientation'          => 'L',
    'title'                => 'Laravel mPDF',
    'author'               => 'مسوده',
    'watermark'            => '',
    'show_watermark'       => true,
    'watermark_font'       => 'sans-serif',
    'display_mode'         => 'fullpage',
    'watermark_text_alpha' => 0.2,
    'custom_font_dir' => base_path('dist/fonts/tajawal/'),
    'custom_font_data' => [
        'tajawal' => [
            'R' => 'Tajawal-Regular.ttf',    // regular font
            //'useOTL' => 0xFF,
            //'useKashida' => 75,
        ]
    ],
    'auto_language_detection'  => false,
    'temp_dir'               => '',
    'pdfa' 			=> false,
    'pdfaauto' 		=> false,
];
``

but I get this error 

Mpdf\MpdfException
Cannot find TTF TrueType font file "Tajawal-Regular.ttf" in configured font directories.

also I get this error

Mpdf\MpdfException
Font "tajawal" is not supported

**Comment by mccarlosen** [comment]
Check the `custom_font_dir`. Try refreshing the configuration cache:

`php artisan config:cache`
