### ISSUE TITLE
breaking css

### ISSUE THREAD

**Issue by robertnicjoo** [mccarlosen/laravel-mpdf#32]
When I load PDF it miss place my data

`Real design`

![download (7)](https://user-images.githubusercontent.com/8672823/88505624-34a59400-d002-11ea-9420-da70b0fb1f71.png)

`What I get in pdf`

![download (8)](https://user-images.githubusercontent.com/8672823/88505662-4ab35480-d002-11ea-8b8d-2e750f0e5259.png)

# Code

`controller`

```php
$data = [
  'foo' => $templateContent
];
$pdf = PDF::loadView('backend.template.pdf', $data);
return $pdf->stream('document.pdf');
```

`view`

```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <body>
        {!! $foo !!}
    </body>
</html>
```
Any idea?

**Comment by mccarlosen** [comment]
Check the styles supported by MPDF. [here](https://mpdf.github.io/css-stylesheets/supported-css.html)
