### ISSUE TITLE
temp_dir default rely on the dir vendor/mpdf/mpdf/tmp to be writabe

### ISSUE THREAD

**Issue by abronin** [mccarlosen/laravel-mpdf#33]
**Problem:**
It is possible to get the error "Temporary files directory "/var/www/app/vendor/mpdf/mpdf/src/Config/../../tmp" is not writable" because of temp_dir is set to the empty string `''` here: https://github.com/mccarlosen/laravel-mpdf/blob/master/src/config/pdf.php#L25 by default.

It's not a problem in the local environment but you can get into trouble when you run the application in Docker (which we do), as an example.

**Solution:**
It would be better to use a system temporary directory in this case. It may look like this:
`'temp_dir' => rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR),`
This code is from widely used `spatie/temporary-directory` and it is heavily tested on all the platforms.

**Comment by mccarlosen** [comment]
Great, good suggestion ;-) - #35 ready
