### ISSUE TITLE
Problem  : data transfer from the controller into the view

### ISSUE THREAD

**Issue by DamienW-dev** [mccarlosen/laravel-mpdf#38]
Hi, 

I have just installed your packages, however I encounter a problem when retrieving my data variables.

I use :
       - carlos-meneses/laravel-mpdf": "2.1.3".
       - "php": "^7.3"
       - "laravel/framework": "^8.0"

here is my code : 

1.  Route : 
```
Route::get('/pdf/{id}/RC_{nof}-{lof}', [RcMtvController::class, 'generate_pdf'])
        ->where('id', '[0-9]+')->where('nof', '[0-9]{6}')->where('lof', '[0-9]{3}')
        ->name('mtv.pdf');
```

2. Controller : 
```
    public function generate_pdf(int $id, int $nof, int $lof) 
	{
		$data = [
                    'titlePDF'` => 'Test PDF',
                    'id'       => $id,
                    'nof'      => $nof,
                    'lof'      => $lof
               ];

		$pdf = \PDF::loadView('PDF/pdf', $data);
                 return $pdf->stream($data['titlePDF'] . '.pdf');
	}
```
3. View : 
```
<?php

dd($data);

?>
```

4. Result :
Undefined variable: data (View: C:\laragon\www\siteName\resources\views\PDF\pdf.blade.php)

thank you in advance for your help.

**Comment by mccarlosen** [comment]
You don't have the data variable defined inside the array. If you want to print the data variable it should be as follows:

```php
$pdf = PDF::loadView('pdfs.document', ['data' => $data]);
```

Please verify your code, before opening a issue.
