### ISSUE TITLE
How can I assign laravel-mpdf {PAGENO} into PHP variable or Insert page no into the database?

### ISSUE THREAD

**Issue by md-asifiqbal** [mccarlosen/laravel-mpdf#39]
How can I assign laravel-mpdf {PAGENO} into PHP variable or Insert page no into the database?

**Comment by mccarlosen** [comment]
`{PAGENO}` cannot be assigned. This is overridden in the template when creating the document.

You can pass the config to the MPDF instance:

```php
$pdf = PDF::loadView("pdf.document", [], [], [
  'pagenumPrefix' => 'Page number ',
  'pagenumSuffix' => ' - ',
  'nbpgPrefix' => ' out of ',
  'nbpgSuffix' => ' pages'
]);

$pdf->getMpdf()->SetHeader('{PAGENO}{nbpg}');
```

I invite you to visit the following links in the MPDF documentation: [Page Numering](https://mpdf.github.io/paging/page-numbering.html#see-also)
