### ISSUE TITLE
How to have some pages display in Portrait view and some in Landscape in the same PDF?

### ISSUE THREAD

**Issue by tcampbPPU** [mccarlosen/laravel-mpdf#44]
I need to create a single PDF with several pages, which includes some of them that need to be displayed in Landscape orientation. Could something like that be possible?

**Comment by mccarlosen** [comment]
To make more complex documents, you can access the MPDF instance through the `getMpdf()` method. For example:

```php
// controller
$data1 = [
    'foo' => 'bar',
];
$data2 = [
    'drink' => 'milk',
];
$pdf = PDF::loadView('pdfs.page1', $data1);
$instance = $pdf->getMpdf(); // get instance
$instance->AddPage("L"); // add new page with landscape orientation
$instance->WriteHTML(View::make('pdfs.page2', $data2)->render()); // set page from view with data

return $pdf->stream('document.pdf');
```

```html
<!-- resources/views/pdfs/page1.blade.php -->
<html>
  <head>
    <title>Document</title>
  </head>
  <body>
    <h1>Page 1</h1>
    <code>{{ $foo }}</code>
  </body>
</html>
```

```html
<!-- resources/views/pdfs/page2.blade.php -->
<html>
  <head>
    <title>Document</title>
  </head>
  <body>
    <h1>Page 2</h1>
    <code>{{ $drink }}</code>
  </body>
</html>
```

**Result**

![image](https://user-images.githubusercontent.com/8524361/108950799-d80c6500-7634-11eb-9080-8a0b0b1d4408.png)

Check the [documentation](https://mpdf.github.io/reference/mpdf-functions/addpage.html) for more useful functions of **mpdf**.

**Comment by tcampbPPU** [comment]
Aaah I see! Great thanks for the help :)
