### ISSUE TITLE
When is PHP 8 supported?

### ISSUE THREAD

**Issue by abumosaab** [mccarlosen/laravel-mpdf#50]
Hello,

Is there any plans to pump this package to PHP 8. 

Thanks.

**Comment by mccarlosen** [comment]
Hi Yes. You've tried...

I have not tried it.

**Comment by abumosaab** [comment]
I have been trying to see if it works with PHP 8 I'm having trouble with outoloading.

**Comment by abumosaab** [comment]
Well, it works but I had to modify the files structure a bit.

**Comment by abumosaab** [comment]
#51 #

**Comment by mccarlosen** [comment]
#51 pull request is checked and ready
