### ISSUE TITLE
As of 03/05 PSR4 is broken

### ISSUE THREAD

**Issue by colinmackinlay** [mccarlosen/laravel-mpdf#52]
```Class Meneses\LaravelMpdf\LaravelMpdfWrapper located in C:/Users/Colin/Websites/CSS/vendor/carlos-meneses/laravel-mpdf/src\LaravelMpdf\LaravelMpdfWrapper.php does not comply with psr-4 autoloading standard. Skipping.```

Downgrading to 2.1.3 still installs OK on  PHP 8

**Comment by hanicab** [comment]
I have the same issue.

My configuration :

php 8.0
laravel 8
composer 2

Downgrading to 2.1.3 still installs OK

**Comment by mccarlosen** [comment]
The problem has been fixed. Thanks for the warning. Version [2.1.6](https://github.com/mccarlosen/laravel-mpdf/releases/tag/2.1.6)

**Comment by colinmackinlay** [comment]
Thank you for the prompt response. The issue is now resolved.
