### ISSUE TITLE
how to generate from view and file in 1 pdf generation

### ISSUE THREAD

**Issue by kusmantopratama** [mccarlosen/laravel-mpdf#53]
how to generate from view and file in 1 pdf generation

**Comment by mccarlosen** [comment]
I do not understand. Can you describe your idea?

**Comment by kusmantopratama** [comment]
i want to generate 1 pdf file from view and pdf file from storage ... 

ex : 
page 1 generate from view
page 2 embed from file pdf .. 

and bundle download or stream in 1 pdf file.

**Comment by mccarlosen** [comment]
You can use the methods: `setSourceFile`,` ImportPage` and `UseTemplate`. Ex:

```php
...
$pdf = PDF::loadView('document', $data);
$mpdf = $pdf->getMpdf();
$pagecount = $mpdf->setSourceFile(storage_path('app/other-document.pdf'));
$tplId = $mpdf->ImportPage($pagecount);
$mpdf->AddPage(); // if loadView is greater than 1
$mpdf->UseTemplate($tplId);

return $pdf->stream('document.pdf');
```
