### ISSUE TITLE
Footer is not showing on each page when change PDF::loadView to PDF::chunkLoadView

### ISSUE THREAD

**Issue by umairali** [mccarlosen/laravel-mpdf#54]
I am using PDF::chunkLoadView function for large data but the footer is only showing on the last page. I want to show the footer on all pages.

**Comment by mccarlosen** [comment]
It is important to put the tag: `<htmlpagefooter />` inside the beginning of the `body`. Ej:

```html
...
<body>
    <htmlpagefooter name="page-footer">
        Your Footer Content
    </htmlpagefooter>
...
```
