### ISSUE TITLE
Images not loading when URL with HTTPs

### ISSUE THREAD

**Issue by demoseed** [mccarlosen/laravel-mpdf#56]
When image URL with HTTPS protocol then images are not loading in the PDF.
Here are example of this issue:
**URL without https:** http://xyz.com/demo.jpg [ It is working ]
**URL with https:** https://xyz.com/demo.jpg [ Not working ]

Please guide me to solve this problem. I hope issue solved as soon as possible.

**Comment by mccarlosen** [comment]
Can you show me an example of code used?

**Comment by mccarlosen** [comment]
There has been no further interaction on the subject.

**Comment by fhtszbd** [comment]
There will be no problem if the protocol of the picture is consistent with the project. For local debugging, the picture of https will not be displayed.
