### ISSUE TITLE
Save pdf file to S3 CloudFront CDN

### ISSUE THREAD

**Issue by umairali** [mccarlosen/laravel-mpdf#57]
I want to save pdf on s3 CloudFront I am using the save method but the file is not saving.

```
$pdf = PDF::chunkLoadView('<html-separator/>', 'pdf.user', $data);
$pdf->save('path');
```

**Comment by mccarlosen** [comment]
The `laravel-mpdf` package not support S3 storage. You can to save the file to local storage and upload it using Laravel's `Storage` facade...

**Comment by umairali** [comment]
ok thank you
