### ISSUE TITLE
How we can run Javascript before making PDF

### ISSUE THREAD

**Issue by usmanibrahim74** [mccarlosen/laravel-mpdf#58]
I have to convert the timestamp into a local timestamp. so I need to run some javascript to do it. but didn't find any way.
mpdf I think allows you to set some options to enable javascript. how we can do it in this package

**Comment by maximus1127** [comment]
have you ever figured out how to do this? same issue for me.

**Comment by mccarlosen** [comment]
You can use the `$mpdf->SetJS()` method to run Acrobat Javascript. Only Acrobat Javascript is supported.

Example: 

```php
// ...
$mpdf = $pdf->getMpdf();
$mpdf->SetJS('app.alert("Hello World")');
```
This will only work after generating the pdf file.

**Comment by mccarlosen** [comment]
There has been no further interaction on this topic. It closes, but you can open it at any time.

**Comment by jasim6423** [comment]
Hi,

I want to add an Image to the pdf with a hyperlink (using javascript) which will open the website in the browser when a user clicks the image. Can you please advise?
