### ISSUE TITLE
shrink_tables_to_fit or autosize="1" is not working

### ISSUE THREAD

**Issue by moon-web28** [mccarlosen/laravel-mpdf#59]
Hello, 

I generate pdf using an HTML table.

I have used many solutions to stop shrik.
e.g 
1) $pdf->getMpdf()->shrink_tables_to_fit = 0; and  ​$pdf->getMpdf()->shrink_tables_to_fit = 1;
2) autosize="1" and autosize="0

but nothing is working, can you tell me what I'm doing wrong?

I'm using "carlos-meneses/laravel-mpdf": "^2.1",

**Comment by mccarlosen** [comment]
Hello, I advise you to raise the problem in the MPDF repository. [MPDF repository](https://github.com/mpdf/mpdf)
