### ISSUE TITLE
 Use a proper webserver for full functionality

### ISSUE THREAD

**Issue by moamahfouz** [mccarlosen/laravel-mpdf#63]
Can not understand why the latest version doesn't work properly on artisan serve? and how to solve the Maximum execution time of 60 seconds exceeded?

**Comment by mccarlosen** [comment]
There is a note about it here: [README.md](https://github.com/mccarlosen/laravel-mpdf#important-notes). You can also check the same note in the MPDF repository [here](https://github.com/mpdf/mpdf#known-server-caveats)
