### ISSUE TITLE
Lists: list_symbol_size not working

### ISSUE THREAD

**Issue by mpageljensen** [mccarlosen/laravel-mpdf#67]
I've tried a number of ways now to make li list bullet items bigger with the mpdf setting: list_symbol_size.
I've attempted implementing it in my pdf config file, and I've also tried including it in the loadView config array, but none of it seems to work, then again I don't get any errors either, so I don't really have a lot to go on :-)

**Comment by mccarlosen** [comment]
Hello, @mpageljensen this bug has been fixed in this [commit](https://github.com/mccarlosen/laravel-mpdf/commit/6e767ed72d705cd52a5eda7b7e5f9b8eaec2f98e). Please upgrade your package.

Thanks.

**Comment by mpageljensen** [comment]
Cool it works! Thanks a lot @mccarlosen!
