### ISSUE TITLE
Show extra html on the last page's footer

### ISSUE THREAD

**Issue by youasl** [mccarlosen/laravel-mpdf#68]
Hi, currently I have a normal footer and everything works as intended.
`<htmlpagefooter name="Footer">`
`<div class="footer">You are reading document X</div>`
`</htmlpagefooter>`

But I want a different output for the last page.
`<htmlpagefooter name="Footer">`
`<div class="footer">You are reading document X</div>`
`<div class="extra">This is the last page.</div>`
`</htmlpagefooter>`

How can I achieve this?

**Comment by mccarlosen** [comment]
With a little googling I was able to find the information.

You can set an `htmlpagefooter` for the last page and then insert it at the end of your content body using `sethtmlpagefooter`. Example:

```html
<htmlpagefooter name="LastPageFooter">
    Show me on the last page
</htmlpagefooter>

<!-- the content -->

<sethtmlpagefooter name="LastPageFooter" value="1" />
```
Source: [Jake Jackson - StackOverflow](https://stackoverflow.com/a/51321138/6855665)

**Comment by youasl** [comment]
Sorry, I already tried that method, but that doesn't work. Maybe other solution?

Here is my full code:
```
<html>
<head>
<style>
    @page { 
		size: auto;
		margin-top: 10cm;
		margin-bottom: 10cm;
		header: html_Header;
		footer: html_Footer;
	}
</style>
</head>

<body>
<htmlpageheader name="Header">
Header here
</htmlpageheader>

<htmlpagefooter name="LastPageFooter">
    Show me on the last page
</htmlpagefooter>

Page 1: Content here
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
Page 2: Content here


<sethtmlpagefooter name="LastPageFooter" value="1" />

<htmlpagefooter name="Footer">
Footer here
</htmlpagefooter>

</body>
</html>
```

**Comment by mccarlosen** [comment]
Try making these changes. 

- You should always wrap the text with html tags
- Add other line breaks to get to the second page.
- Rearrange things.

```html
<html>
<head>
<style>
    @page { 
        size: auto;
        margin-top: 10cm;
        margin-bottom: 10cm;
        header: html_Header;
        footer: html_Footer;
    }
</style>
</head>

<body>
<htmlpageheader name="Header">
Header here
</htmlpageheader>

<htmlpagefooter name="Footer">
Footer here
</htmlpagefooter>

<htmlpagefooter name="LastPageFooter">
    Show me on the last page
</htmlpagefooter>

<p>Page 1: Content here</p>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<p>Page 2: Content here</p>

<sethtmlpagefooter name="LastPageFooter" value="1" />

</body>
</html>
```

**Comment by youasl** [comment]
It's working now. Thanks for your quick responses.
