### ISSUE TITLE
how to remove xml version tag when QRCode is created

### ISSUE THREAD

**Issue by da-production** [mccarlosen/laravel-mpdf#71]
i'm using https://github.com/SimpleSoftwareIO/simple-qrcode to generate QRCode and is printing the comment of the svg format <?"encoding="UTF-8 xml version="1.0"?>

**Comment by mccarlosen** [comment]
I recommend that you use the embed option. Since the only way to remove that tag is to process the output of the `generate` method before printing it to the PDF.

![image](https://user-images.githubusercontent.com/8524361/145152752-5b449aa2-3719-4ef1-b765-4a4b6bb94081.png)

Example using base64:

```html
<img src="data:image/png;base64,{!! base64_encode(QrCode::format('png')->margin(0)->size(93)->generate(
    'Hello World'
)) !!}" alt="QrCode">
```
