### ISSUE TITLE
custom font not picked up

### ISSUE THREAD

**Issue by karunkshrestha** [mccarlosen/laravel-mpdf#77]
I am having the similar issue where the custom fonts are not picked up.
config:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/5154097/149950999-276c7364-426a-463b-846d-e8cb8ea1a7f3.png">

fonts:
<img width="152" alt="image" src="https://user-images.githubusercontent.com/5154097/149951040-a66b8025-5742-4300-9c72-8e69ed43d2b8.png">

load view:
$pdf = PDF::loadView('emails.test.view',['data' => $this->data]);

Result: defaults to dejavu font
<img width="54" alt="image" src="https://user-images.githubusercontent.com/5154097/149951254-70b911a5-68a0-47ab-a4c7-3d0cc3ca6557.png">

_Originally posted by @karunkshrestha in https://github.com/mccarlosen/laravel-mpdf/issues/11#issuecomment-1015438260_

**Comment by karunkshrestha** [comment]
That didn't work.
I renamed the font files as suggested
fonts:
<img width="140" alt="image" src="https://user-images.githubusercontent.com/5154097/149978907-705ab8d7-57ac-4705-9421-06d1b8d72dd7.png">

setup the config:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/5154097/149979017-9972146e-f450-4971-919c-586031750053.png">

updated the css:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/5154097/149979068-6dc25987-62f0-4538-a858-d8db215fccd8.png">

Resulting pdf font uses dejavu
<img width="38" alt="image" src="https://user-images.githubusercontent.com/5154097/149979205-0363c69c-1a29-4fd6-9332-628f09519c44.png">

simply renaming the font to "couriernew" works fine.
<img width="320" alt="image" src="https://user-images.githubusercontent.com/5154097/149979491-2437f7df-7e73-41fa-9041-c512c76ad06d.png">

Resulting pdf font properties
<img width="195" alt="image" src="https://user-images.githubusercontent.com/5154097/149979573-81180c8d-c9e0-4f4b-b9f6-ef6617326739.png">

**Comment by RabeeaAli** [comment]
I think you should use these to options after the last thing:

```
  'useOTL' => 0xFF,
  'useKashida' => 75,
```

https://stackoverflow.com/questions/17586409/adding-font-to-mpdf/57162534#57162534

**Comment by Ammar09** [comment]
try this:

**body {
            font-family: 'courier' , sans;
        }**
