### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by omdesignz** [mccarlosen/laravel-mpdf#79]
Hi there,
I was just wondering if this package works with Laravel 9. I recently updated a project that uses this package to L9 and  got the following error:

`Declaration of Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void`

I'm about to try downgrading the PSR Logger package version to see if it solves the problem.

I've gone through every possible cenario but haven't come up with an answer yet. Any insight would be appreciated.

**Comment by omdesignz** [comment]
Hi there,
It seems that the problem is solved by using v8.0.17 of mpf. Currently this package pulls in v8.0.16.

**Comment by mrdigitalau** [comment]
> Hi there, It seems that the problem is solved by using v8.0.17 of mpf. Currently this package pulls in v8.0.16.

Hi Omdesignz, how did you go about changing the verion of MPDF used with this package specifically? Cheers

**Comment by mrdigitalau** [comment]
Sorry, for anyone else asking, just add  "mpdf/mpdf": "^8.0.17" to your composer.json and reinstall - it will override what this package uses. Cheers

**Comment by omdesignz** [comment]
> > Hi there, It seems that the problem is solved by using v8.0.17 of mpf. Currently this package pulls in v8.0.16.
> 
> 
> 
> Hi Omdesignz, how did you go about changing the verion of MPDF used with this package specifically? Cheers

Sorry for not getting back to you. Had a backlog of work to get through 😅.
