### ISSUE TITLE
Laravel 9 error declaration of setLogger not compatible with Psr

### ISSUE THREAD

**Issue by zulhilmixrahman** [mccarlosen/laravel-mpdf#80]
After trying upgrade to Laravel 9, an error of declaration of setLogger must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void occurred. 

![laravel 9 mpdf](https://user-images.githubusercontent.com/1441729/155482692-a3f8e1c6-ecbe-4da2-8370-63417520573f.png)

https://flareapp.io/share/47q10E07#F1

**Comment by zulhilmixrahman** [comment]
Sorry, overlooked in closed issue section.

**Comment by mrdigitalau** [comment]
Hi mate, any chance you can elaborate on what you did to fix the issue? Cheers

**Comment by mrdigitalau** [comment]
Sorry, for anyone else asking, just add "mpdf/mpdf": "^8.0.17" to your composer.json and reinstall - it will override what this package uses. Cheers

**Comment by realtebo** [comment]
So we fix downgrading?
