### ISSUE TITLE
Custom font not working

### ISSUE THREAD

**Issue by agares29** [mccarlosen/laravel-mpdf#84]
I'm trying to add a custom font, but it's not working.
I've already tried all the solutions from previous issues but neither of them works for me. I don't see what I'm missing

I already create the config/pdf.php file:

![pdf](https://user-images.githubusercontent.com/59162998/160884513-1cf23f28-950a-484f-89c5-5b2a57ab8725.png)

Added the fonts to the project, in this case I use the public folder, also tried to put them on resources folder, but not working:

![fonts](https://user-images.githubusercontent.com/59162998/160884697-8987a812-5f1c-439b-8250-ed1504dfb2de.png)

And this is how I'm setting the font on the blade file:

![code](https://user-images.githubusercontent.com/59162998/160885032-a667be71-3754-40a2-9c6c-16ea0f81936a.png)

**Comment by tek2991** [comment]
Any update on this?

**Comment by agares29** [comment]
@tek2991, unfortunately not, I changed to this library niklasravnsborg/laravel-pdf, it worked great and the changes to the code where insignificant

**Comment by mccarlosen** [comment]
Hi guys,

This is my config in `pdf.php` file and I don't have any problem. Follow these tips:

- Write filename in CamelCase.
- The name must be the same as the font name.
- The font type must follow the name. Example: `Roboto-Regular`, `Roboto-Italic`, `Roboto-Bold`.

![image](https://user-images.githubusercontent.com/8524361/171319267-783f5bf0-a6f8-402b-81e8-528b7f7d4014.png)

![image](https://user-images.githubusercontent.com/8524361/171318816-96560ff4-fdd6-47f2-bcaa-7697e5c8ba6b.png)

![image](https://user-images.githubusercontent.com/8524361/171319095-2366482b-dbb0-4939-8761-aaf55aff278c.png)
