### ISSUE TITLE
Arabic 

### ISSUE THREAD

**Issue by da-production** [mccarlosen/laravel-mpdf#86]
Hi Cairo Fonts doesn't work i followed the documentation

**Comment by kreemov** [comment]
hi, 

only traditionalarabic.ttf worked with me

**Comment by mccarlosen** [comment]
Same issue here: #84.

Follow these tips:

https://github.com/mccarlosen/laravel-mpdf/issues/84#issuecomment-1143066219

**Comment by bestiony** [comment]
putting this here so I find it in the next project , this is how you solve individual letters rendering problem 
[https://github.com/mccarlosen/laravel-mpdf/issues/73#issuecomment-1012043629](url)
