### ISSUE TITLE
[Feature request] Please make MPdf Macroable

### ISSUE THREAD

**Issue by realtebo** [mccarlosen/laravel-mpdf#87]
Hi !

As title, we ask you kindly to implement Macroable in this project so we can add macro instead of creating custom helpers as shortcut.

**Comment by newton4al** [comment]
@mccarlosen thanks a bunch for this wrapper.

Could you help us pop the Macroable trait in the LaravelMpdf?

**Comment by mccarlosen** [comment]
Hi guys!

Could you give me an example? How would you use it?

**Comment by newtonjob** [comment]
@mccarlosen 

By adding the Macroable trait to the LaravelMpdf, we could extend the class with custom methods for our own use case.

For example, I may want to add a method that returns a base64 representation of the Pdf string.

```php
LaravelMpdf::macro('base64', function () {
    return base64_encode($this->output());
});
```

Then it could be used like so;

```php
$base64_string = PDF::loadView('pdf.document', $data)->base64();
```

Thanks

**Comment by realtebo** [comment]
Also, we can create a ::init to return a new instance with some defaults about security, etc
