### ISSUE TITLE
PDF Preview instead of download

### ISSUE THREAD

**Issue by sarveshamrit** [mccarlosen/laravel-mpdf#88]
Hello sir, Can u plz help how to preview pdf in browser instead of download ?

i am using below function now :

PDF::loadView('invoice.bill-invoice', ['data' => $InvoiceData], [], [
            'title' => 'Another Title',
            'margin_top' => 0
        ])->save($file_path);

**Comment by mccarlosen** [comment]
Hello, @sarveshamrit 

You can use the `stream` method for it.

Example:
```php
$pdf = PDF::loadView('invoice.bill-invoice', ['data' => $InvoiceData], [], [
   'title' => 'Another Title',
   'margin_top' => 0
]);

return $pdf->stream();
```
