### ISSUE TITLE
Error Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with  in production 

### ISSUE THREAD

**Issue by ntnngan210** [mccarlosen/laravel-mpdf#90]
When I deploy the production ,  I encountered this error :" local.ERROR: Declaration of Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of Mpdf\\Mpdf::setLogger(Psr\\Log\\LoggerInterface $logger) must be compatible with Psr\\Log\\LoggerAwareInterface::setLogger(Psr\\Log\\LoggerInterface $logger): void at /var/www/html/vendor/mpdf/mpdf/src/Mpdf.php:1569) "

**Comment by Haris1566** [comment]
just Run These  Two Commands on your terminal
`composer remove psr/log

composer require psr/log=v2.*`
