### ISSUE TITLE
Failed to download mpdf/mpdf 

### ISSUE THREAD

**Issue by aamalomari** [mccarlosen/laravel-mpdf#91]
**hello,
I tried many times to install package but I got this error**

`λ composer require carlos-meneses/laravel-mpdf
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^2.1 for carlos-meneses/laravel-mpdf
./composer.json has been updated
Running composer update carlos-meneses/laravel-mpdf
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Downloading setasign/fpdi (v2.3.6)
  - Downloading php-http/message-factory (v1.0.2)
  - Downloading paragonie/random_compat (v9.99.100)
  - Downloading mpdf/mpdf (v8.1.2)
  - Downloading carlos-meneses/laravel-mpdf (2.1.8)
 4/5 [======================>-----]  80%A connection timeout was encountered. If you intend to run Composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make Composer run in offline mode.
  - Downloading mpdf/mpdf (v8.1.2)
  - Downloading mpdf/mpdf (v8.1.2)
  - Downloading mpdf/mpdf (v8.1.2)
    Failed to download mpdf/mpdf from dist: curl error 28 while downloading https://codeload.github.com/mpdf/mpdf/legacy.zip/a8a22f4874157e490d41b486053a20bec42e182c: Operation timed out after 300007 milliseconds with 4344624 out of 46591941 bytes received
    Now trying to download from source
 5/5 [============================] 100%
In GitDownloader.php line 82:

  git was not found in your PATH, skipping source download

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
`

**Comment by mccarlosen** [comment]
That error is not related to the *LaravelMpdf* package. Please, verify your internet connection or your network.
