### ISSUE TITLE
Class 'App\Http\Controllers\PDF' not found

### ISSUE THREAD

**Issue by aamalomari** [mccarlosen/laravel-mpdf#92]
hello 

I got this error only in the controller, I use it in routeweb.php its working
I'm using laravel  8.83.23

error:
**Class 'App\Http\Controllers\PDF' not found**

controller  code:

        $users = \App\Models\User::get();
        $pdf = PDF::loadView('pdf', compact('users'));
        return $pdf->stream(Str::uuid()->toString(). '-' .  date('Y-m-d H:i:s'). '.pdf');

**Comment by mccarlosen** [comment]
Did you include `use PDF;` at the beginning of class?

**Comment by aamalomari** [comment]
> Did you include `use PDF;` at the beginning of class?
> 
> 
> 
> Review the [documentation](https://github.com/mccarlosen/laravel-mpdf#installation) of installation.

Sorry I forgot that, It's working.
But fonts not working it's working only with watermark 

When I back to version 2.1.3 it's working, I don't know about other versions, I work with 2.1.9
