### ISSUE TITLE
Showing Error - Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger)

### ISSUE THREAD

**Issue by rakesh3899** [mccarlosen/laravel-mpdf#94]
After completing all procedures, when I like to visit the specific routes, then it's giving an error that is given below.
Declaration of Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void

**Comment by shukriYusof** [comment]
@rakesh3899  maybe you could refer to this https://stackoverflow.com/a/73210063

**Comment by hsmfawaz** [comment]
Fixed by installing the latest version
