### ISSUE TITLE
Header and Footer can not be set at the center of page

### ISSUE THREAD

**Issue by Arman8852** [mccarlosen/laravel-mpdf#96]
I am trying to generate pdf where the header and footer will be at the center of each page. I have added this to my blade view file:

```
<htmlpageheader class='text-center' name="page-header">
   www.amazon.com
</htmlpageheader>

<htmlpagefooter  class='text-center' name="page-footer" >
  www.amazon.com
</htmlpagefooter>
```

and then added this to CSS:

`@page {header: page-header; footer: page-footer;}`

in my controller:

```
use PDF;
public function Downloadpdf($id)
    {
     $product = Product::find($id);
     $pdf = PDF::loadView('template',compact('product'));
     return $pdf->stream('invoice.pdf');
    } 
```

headers and footers now are right-aligned but I want them to be center-aligned. So I add this inside @page in my CSS:
`header-margin: 50mm;`

But there is no option of margin-right or margin-left for header or footer. So, the margin is working on all 4 sides. But I only want them to be at the center of the page without any margin.

**Comment by mccarlosen** [comment]
You can use table elements to wrap your content. For example:

```css
.table {
    width: 100%;
}
```

```html
<table class="table" cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td align="center">
           www.amazon.com
        </td>
    </tr>
</table>
```

Note: My advice is to always wrap your content with HTML  elements.

**Comment by Arman8852** [comment]
Thanks a lot @mccarlosen. Working just fine!!!
