### ISSUE TITLE
Undefined variable $cw

### ISSUE THREAD

**Issue by AndrewRamyE** [mccarlosen/laravel-mpdf#98]
the issue Undefined variable $cw
vendor/mpdf/mpdf/src/Mpdf.php:3991

**Comment by rkpontes** [comment]
I'm having the same problem

**Comment by MubinSayed** [comment]
Same problem here

**Comment by mccarlosen** [comment]
Insufficient information. You should show environment configuration information. PHP version, framework version...

**Comment by AndrewRamyE** [comment]
PHP version 8.0.1 and framework version laravel 8.6
